
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: azdevops
    app.kubernetes.io/name: azdevops
  name: azdevops
---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azdevops
data:
  AZP_TOKEN: {{AZP_TOKEN}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azdevops
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: localhost:5001/azp-agent:{{SCALE_TYPE}}
        env:
          - name: AZP_URL
            value: "{{AZP_URL}}"
          - name: AZP_POOL
            value: "{{AZP_POOL}}"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
  namespace: azdevops
data:
  personalAccessToken: {{AZP_TOKEN}}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
  namespace: azdevops
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
  namespace: azdevops
spec:
  scaleTargetRef:
    name: azdevops-deployment
  minReplicaCount: 2
  maxReplicaCount: 5 
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "1"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: pipeline-trigger-auth